from tissue.estimators.base_estimator import Estimator, EstimatorGraph, EstimatorNoGraph

from tissue.estimators.estimator_gat import EstimatorGAT
from tissue.estimators.estimator_gcn import EstimatorGCN
from tissue.estimators.estimator_gsum import EstimatorGsum
from tissue.estimators.estimator_multi_instance import EstimatorMultiInstance
#from tissue.estimators.estimator_multi_instance import EstimatorMultiInstanceDispersion
from tissue.estimators.estimator_reg import EstimatorREG, EstimatorREGDispersion